[local]
localhost ansible_connection=local

[webservers]
localhost ansible_connection=local

[test_env:children]
local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
app_port=3000
app_name=oqlos-portal
deploy_dir=/opt/oqlos/www
